=== kai8406/MavenOneCMDB/org.onecmdb.core/src/main/other/conf/onecmdb.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT instances EMPTY>

<!ELEMENT onecmdb (templates|instances)*>

<!ELEMENT templates (template)*>

<!ELEMENT template (description | derivedFrom | attribute | setSimpleValue | setComplexValue)+>
<!ATTLIST template
	alias CDATA #REQUIRED
	displayName CDATA #IMPLIED
>
<!ELEMENT derivedFrom (ref)>

<!ELEMENT attribute (simpleType?, complexType?, policy?, description?)>
<!ATTLIST attribute
	attAlias CDATA #REQUIRED
	displayName CDATA #IMPLIED
>
<!ELEMENT simpleType (#PCDATA)>
<!ELEMENT complexType (ref, refType?)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT policy (minOccurs?, maxOccurs?, required?)>
<!ELEMENT maxOccurs (#PCDATA)>
<!ELEMENT minOccurs (#PCDATA)>
<!ELEMENT required EMPTY>

<!ELEMENT setSimpleValue (#PCDATA)>
<!ATTLIST setSimpleValue
	attAlias CDATA #REQUIRED
>

<!ELEMENT setComplexValue (ref)>
<!ATTLIST setComplexValue
	attAlias CDATA #REQUIRED
>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
	alias CDATA #REQUIRED
>

<!ELEMENT refType (ref)>

=== kai8406/MavenOneCMDB/ROOT/src/main/resources/org/onecmdb/core/internal/job/JobSchema.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- 
<!DOCTYPE onecmdb SYSTEM "onecmdb.dtd">
 -->
<onecmdb>
	<templates>
	
		<!--  Refrence Definition -->
		<template alias="JobReference" displayName="JobReference">
			<derivedFrom><ref alias="Reference"/></derivedFrom>
		</template>
		
		<template alias="JobTriggerReference" displayName="JobTriggerReference">
			<derivedFrom><ref alias="JobReference"/></derivedFrom>
		</template>
	
		<template alias="JobProcessReference" displayName="JobProcessReference">
			<derivedFrom><ref alias="JobReference"/></derivedFrom>
		</template>
		
		
		<!-- Root Job Template -->
		<template alias="Job" displayName="Job">
			<derivedFrom><ref alias="Root"/></derivedFrom>
			<description>The master template for Jobs. You also need a trigger to start a job.</description>
			<setSimpleValue attAlias="icon">job</setSimpleValue>
		</template>
		
		<!--  Trigger definition -->
		<template alias="JobTrigger" displayName="JobTrigger">
			<derivedFrom><ref alias="Job"/></derivedFrom>
			<description>Master template for job triggers. To start a job a trigger is required.</description>			
			<attribute attAlias="process" name="Process to trigger">
				<complexType>
					<ref alias="JobProcess"/>
					<refType><ref alias="JobTriggerReference"/></refType>
				</complexType>
			</attribute>
			<attribute attAlias="start" name="Last triggered">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="stop" name="Last ended">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="user" name="User">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="password" name="Password">
				<simpleType>xs:password</simpleType>
			</attribute>
			
		</template>
		
		<template alias="JobManualTrigger" displayName="JobManuallyTrigger">
			<derivedFrom><ref alias="JobTrigger"/></derivedFrom>
			<description>Template for manual triggers. Use this template if you want to start a job with the Start button.</description>			
		</template>
		
		<template alias="JobSchedulareTrigger" displayName="JobSchedulareTrigger">
			<derivedFrom><ref alias="JobTrigger"/></derivedFrom>
			<description>Master template for scheduled triggers.</description>
		</template>
		
		<template alias="JobCronTrigger" displayName="JobCronTrigger">
			<derivedFrom><ref alias="JobSchedulareTrigger"/></derivedFrom>
			<description>Cron like trigger.</description>			
			<attribute attAlias="cronExpression" displayName="Cron Expression">
				<simpleType>xs:string</simpleType>
			</attribute>
		</template>
		
		<template alias="JobIntervallTrigger" displayName="JobIntervallTrigger">
			<derivedFrom><ref alias="JobSchedulareTrigger"/></derivedFrom>
			<description>A basic intervall trigger.</description>			
			<attribute attAlias="startDelay" displayName="Start Delay">
				<simpleType>xs:integer</simpleType>
			</attribute>
			<attribute attAlias="repeateIntervall" displayName="Repeate Intervall">
				<simpleType>xs:integer</simpleType>
			</attribute>
			<attribute attAlias="repeateCount" displayName="Repeate Count">
				<simpleType>xs:integer</simpleType>
			</attribute>
		</template>
	
		<!-- Job Process -->
		<template alias="JobProcess" displayName="JobProcess">
			<derivedFrom><ref alias="Job"/></derivedFrom>
			<description>Master template for definitions of jobs.</description>
			<attribute attAlias="javaClass" name="Java class">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="start" name="Last Started">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="stop" name="Last Stopped">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="state">
				<description>Internal state of a process (IDLE|RUNNING).</description>
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="status">
				<description>Internal status of a process Started|Completed|Failed</description>
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="progress">
				<description>Progress information that the external job program controls. Value can be any text.</description>
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="progressPercentage">
				<description>Progress that the external job program controls, value from 0 to 100</description>
				<simpleType>xs:integer</simpleType>
			</attribute>
			<setSimpleValue attAlias="state">IDLE</setSimpleValue>
		</template>
	</templates>
</onecmdb>

=== kai8406/MavenOneCMDB/org.onecmdb.core/src/main/java/org/onecmdb/core/internal/reference/ReferenceSchema.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- 
<!DOCTYPE onecmdb SYSTEM "onecmdb.dtd">
 -->
<onecmdb>
	<templates>
    <!--  Reference definition -->
		<template alias="Reference" displayName="Reference">
			<derivedFrom><ref alias="Root"/></derivedFrom>
			<description>Master template for references.</description>			
			<attribute attAlias="target" displayName="Target">
				<description>The target of this reference</description>
				<complexType>
					<ref alias="Root"/>
				</complexType>
			</attribute>
			<attribute attAlias="source" displayName="Source">
				<description>The source of this reference</description>
				<complexType>
					<ref alias="Root"/>
				</complexType>
			</attribute>
			
			<setSimpleValue attAlias="icon">reference</setSimpleValue>
		</template>
	
		<template alias="CIReference" displayName="CIReference">
			<derivedFrom><ref alias="Reference"/></derivedFrom>
			<description>Master template for CI references.</description>			
			<setSimpleValue attAlias="icon">reference</setSimpleValue>
		</template>
	</templates>
	
</onecmdb>

=== kai8406/MavenOneCMDB/org.onecmdb.core/src/main/java/org/onecmdb/core/internal/authorization/RBACSchema.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- 
<!DOCTYPE onecmdb SYSTEM "onecmdb.dtd">
 -->
<onecmdb>
	<templates>
	
		<template alias="RBAC" displayName="RBAC">
			<derivedFrom><ref alias="Root"/></derivedFrom>
			<description>This describes the RBAC objects in OneCMDB.</description>
		</template>
		
		
		
		<template alias="CMDBRole" displayName="${name}">
			<derivedFrom><ref alias="RBAC"/></derivedFrom>
			<description>This describes one role in OneCMDB.</description>
			
			<attribute attAlias="name" displayName="Name">
				<simpleType>xs:string</simpleType>
			</attribute>
			
			<attribute attAlias="permission" displayName="Permissions">
				<description>The permissions connected to this role</description>
				<complexType>
					<ref alias="CMDBSecurityPermission"/>
					<refType><ref alias="Reference"/></refType>
				</complexType>
				<policy>
					<maxOccurs>unbound</maxOccurs>
					<minOccurs>0</minOccurs>
				</policy>
			</attribute>
			<setSimpleValue attAlias="name">Role</setSimpleValue>
		</template>

		<template alias="CMDBSecurityGroup" displayName="${name}">
			<derivedFrom><ref alias="RBAC"/></derivedFrom>
			<description>This describes one group in OneCMDB.</description>
			<attribute attAlias="children" displayName="Children Group(s)">
				<description>The child security groups</description>
				<complexType>
					<ref alias="CMDBSecurityGroup"/>
					<refType><ref alias="Reference"/></refType>
				</complexType>
				<policy>
					<maxOccurs>unbound</maxOccurs>
					<minOccurs>0</minOccurs>
				</policy>
			</attribute>
			<attribute attAlias="name" displayName="Group Name">
				<description>The symbolic name for this security group</description>
				<simpleType>xs:string</simpleType>
			</attribute>
			<setSimpleValue attAlias="name">SecurityGroup</setSimpleValue>
		</template>

		<template alias="CMDBSecurityPermission" displayName="CMDBSecurityPermissions">
			<derivedFrom><ref alias="RBAC"/></derivedFrom>
			<description>This describes one role in OneCMDB.</description>
		</template>
		
		<template alias="CMDBSecurityGroupPermission" displayName="SGP R[${read}]W[${write}]C[${create}]D[${delete}]">
			<derivedFrom><ref alias="CMDBSecurityPermission"/></derivedFrom>
			<description>This describes one group permission in OneCMDB.</description>
				
			<attribute attAlias="group" displayName="Group">
				<description>The permissions connected to this role</description>
				<complexType>
					<ref alias="CMDBSecurityGroup"/>
					<refType><ref alias="Reference"/></refType>
				</complexType>
				<policy>
					<maxOccurs>unbound</maxOccurs>
					<minOccurs>0</minOccurs>
				</policy>
			</attribute>
			
			<attribute attAlias="read" displayName="Read">
				<description>Read permission the groups</description>
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="write" displayName="Write">
				<description>Write permission the groups</description>
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="delete" displayName="Delete">
				<description>Delete permission the groups</description>
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="create" displayName="Create">
				<description>Create permission the groups</description>
				<simpleType>xs:boolean</simpleType>
			</attribute>
		</template>

	</templates>
	
	<instances>
		<CMDBSecurityGroup alias="RootGroup">
			<name>RootGroup</name>
		</CMDBSecurityGroup>
		<!--  
		<CMDBRole alias="Role_CMDBAdmin">
			<permission><ref alias="AdminGroupPermission"/></permission>
		</CMDBRole>
	
		<CMDBRole alias="Role_CMDBReadOnly">
			<permission><ref alias="ReadonlyGroupPermission"/></permission>
		</CMDBRole>
		
		<CMDBSecurityGroupPermission alias="AdminGroupPermission">
			<read>true</read>
			<write>true</write>
			<delete>true</delete>
			<create>true</create>
			<group><ref alias="RootGroup"/></group>
		</CMDBSecurityGroupPermission>
		
		<CMDBSecurityGroupPermission alias="ReadonlyGroupPermission">
			<read>true</read>
			<write>false</write>
			<delete>false</delete>
			<create>false</create>
			<group><ref alias="RootGroup"/></group>
		</CMDBSecurityGroupPermission>
		-->
	</instances>

</onecmdb>

=== kai8406/MavenOneCMDB/ROOT/src/main/resources/org/onecmdb/core/internal/authentication/UserSchema.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- 
<!DOCTYPE onecmdb SYSTEM "onecmdb.dtd">
 -->
<onecmdb>
	<templates>
	
		<!--  Refrence Definition -->
		<template alias="CMDBAccount" displayName="${username}">
			<derivedFrom><ref alias="Root"/></derivedFrom>
			<description>This describes one user account in OneCMDB.</description>
		
			<attribute attAlias="username" displayName="Username">
				<simpleType>xs:string</simpleType>
			</attribute>
			<attribute attAlias="password" displayName="Password">
				<simpleType>xs:password</simpleType>
			</attribute>
			<attribute attAlias="enabled" displayName="Enabled">
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="accountExpired" displayName="Account Expired">
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="credentialsExpired" displayName="Credential Expired">
				<simpleType>xs:boolean</simpleType>
			</attribute>
			<attribute attAlias="accountLocked" displayName="Account Locked">
				<simpleType>xs:boolean</simpleType>
			</attribute>
			
			<attribute attAlias="role" displayName="Role">
				<simpleType>xs:string</simpleType>
				<policy>
					<minOccurs>0</minOccurs>
					<maxOccurs>unbound</maxOccurs>
				</policy>			
			</attribute>
			<attribute attAlias="defaultRole" displayName="Default Role">
				<simpleType>xs:string</simpleType>
				<policy>
					<minOccurs>1</minOccurs>
					<maxOccurs>1</maxOccurs>
				</policy>			
			</attribute>
			
	
			<setSimpleValue attAlias="enabled">true</setSimpleValue>
			<setSimpleValue attAlias="accountExpired">false</setSimpleValue>
			<setSimpleValue attAlias="credentialsExpired">false</setSimpleValue>			
			<setSimpleValue attAlias="accountLocked">false</setSimpleValue>
			<setSimpleValue attAlias="username">Account</setSimpleValue>			
			<setSimpleValue attAlias="icon">useraccount</setSimpleValue>
		</template>
	</templates>
	
	<instances>
		
	</instances>

</onecmdb>
